import IEmployee from "@/types/table-employee-type";

export const employees: IEmployee[] = [
    {
        id: "EMP001",
        name: "Avinash Gupta",
        position: "Software Engineer",
        department: "IT",
        joiningDate: "24th July 2024",
        status: "Inactive",
    },
    {
        id: "EMP002",
        name: "John Doe",
        position: "Project Manager",
        department: "Management",
        joiningDate: "15th March 2021",
        status: "Active",
    },
    {
        id: "EMP003",
        name: "Jane Smith",
        position: "HR Specialist",
        department: "Human Resources",
        joiningDate: "12th August 2020",
        status: "Active",
    },
    {
        id: "EMP004",
        name: "Alice Johnson",
        position: "Marketing Manager",
        department: "Marketing",
        joiningDate: "7th January 2022",
        status: "Inactive",
    },
    {
        id: "EMP005",
        name: "Robert Brown",
        position: "Sales Executive",
        department: "Sales",
        joiningDate: "19th October 2021",
        status: "Active",
    },
    {
        id: "EMP006",
        name: "Michael White",
        position: "Financial Analyst",
        department: "Finance",
        joiningDate: "3rd May 2020",
        status: "Inactive",
    },
    {
        id: "EMP007",
        name: "William Harris",
        position: "Data Scientist",
        department: "IT",
        joiningDate: "14th November 2019",
        status: "Active",
    },
    {
        id: "EMP008",
        name: "David Clark",
        position: "DevOps Engineer",
        department: "IT",
        joiningDate: "30th June 2023",
        status: "Active",
    },
    {
        id: "EMP009",
        name: "Emma Lewis",
        position: "UI/UX Designer",
        department: "Design",
        joiningDate: "18th April 2022",
        status: "Inactive",
    },
    {
        id: "EMP010",
        name: "Sophia Lee",
        position: "Content Writer",
        department: "Marketing",
        joiningDate: "22nd February 2021",
        status: "Active",
    },
    {
        id: "EMP011",
        name: "James Walker",
        position: "Network Engineer",
        department: "IT",
        joiningDate: "11th December 2020",
        status: "Active",
    },
    {
        id: "EMP012",
        name: "Mia Hall",
        position: "Product Manager",
        department: "Management",
        joiningDate: "27th July 2019",
        status: "Inactive",
    },
    {
        id: "EMP013",
        name: "Liam Allen",
        position: "Quality Analyst",
        department: "Quality Assurance",
        joiningDate: "8th September 2021",
        status: "Active",
    },
    {
        id: "EMP014",
        name: "Noah King",
        position: "Support Specialist",
        department: "Customer Support",
        joiningDate: "5th October 2020",
        status: "Inactive",
    },
    {
        id: "EMP015",
        name: "Ethan Wright",
        position: "System Administrator",
        department: "IT",
        joiningDate: "23rd January 2023",
        status: "Active",
    },
    {
        id: "EMP016",
        name: "Olivia Scott",
        position: "Graphic Designer",
        department: "Design",
        joiningDate: "17th March 2021",
        status: "Active",
    },
    {
        id: "EMP017",
        name: "Isabella Green",
        position: "Business Analyst",
        department: "Finance",
        joiningDate: "9th April 2022",
        status: "Inactive",
    },
    {
        id: "EMP018",
        name: "Charlotte Adams",
        position: "SEO Specialist",
        department: "Marketing",
        joiningDate: "4th May 2020",
        status: "Active",
    },
    {
        id: "EMP019",
        name: "Lucas Nelson",
        position: "Mobile Developer",
        department: "IT",
        joiningDate: "21st June 2021",
        status: "Active",
    },
    {
        id: "EMP020",
        name: "Amelia Carter",
        position: "Digital Marketer",
        department: "Marketing",
        joiningDate: "29th July 2023",
        status: "Inactive",
    },
    {
        id: "EMP021",
        name: "Mason Mitchell",
        position: "Software Tester",
        department: "Quality Assurance",
        joiningDate: "12th February 2020",
        status: "Active",
    },
    {
        id: "EMP022",
        name: "Avery Perez",
        position: "Cloud Engineer",
        department: "IT",
        joiningDate: "1st August 2021",
        status: "Active",
    },
    {
        id: "EMP023",
        name: "Evelyn Roberts",
        position: "Accountant",
        department: "Finance",
        joiningDate: "6th September 2022",
        status: "Inactive",
    },
    {
        id: "EMP024",
        name: "Harper Lewis",
        position: "Social Media Manager",
        department: "Marketing",
        joiningDate: "16th October 2019",
        status: "Active",
    },
    {
        id: "EMP025",
        name: "Benjamin Baker",
        position: "Web Developer",
        department: "IT",
        joiningDate: "10th November 2021",
        status: "Active",
    },
    {
        id: "EMP026",
        name: "Aiden Hill",
        position: "IT Support",
        department: "IT",
        joiningDate: "24th December 2020",
        status: "Inactive",
    },
    {
        id: "EMP027",
        name: "Ella Ramirez",
        position: "Legal Advisor",
        department: "Legal",
        joiningDate: "13th January 2022",
        status: "Active",
    },
    {
        id: "EMP028",
        name: "Emily Martinez",
        position: "Operations Manager",
        department: "Operations",
        joiningDate: "22nd February 2023",
        status: "Active",
    },
    {
        id: "EMP029",
        name: "Jacob Anderson",
        position: "Cybersecurity Analyst",
        department: "IT",
        joiningDate: "27th March 2020",
        status: "Inactive",
    },
    {
        id: "EMP030",
        name: "Madison Thomas",
        position: "Recruiter",
        department: "Human Resources",
        joiningDate: "7th April 2021",
        status: "Active",
    },
    {
        id: "EMP031",
        name: "Henry Rodriguez",
        position: "Back-end Developer",
        department: "IT",
        joiningDate: "15th May 2020",
        status: "Active",
    },
    {
        id: "EMP032",
        name: "Alexander Lee",
        position: "Technical Writer",
        department: "IT",
        joiningDate: "30th June 2022",
        status: "Inactive",
    },
    {
        id: "EMP033",
        name: "Sebastian Walker",
        position: "Data Analyst",
        department: "Finance",
        joiningDate: "14th July 2021",
        status: "Active",
    },
    {
        id: "EMP034",
        name: "Zoey King",
        position: "HR Generalist",
        department: "Human Resources",
        joiningDate: "25th August 2023",
        status: "Active",
    },
    {
        id: "EMP035",
        name: "Levi Hall",
        position: "Full Stack Developer",
        department: "IT",
        joiningDate: "5th September 2019",
        status: "Inactive",
    },
    {
        id: "EMP036",
        name: "Grace Allen",
        position: "Compliance Officer",
        department: "Legal",
        joiningDate: "18th October 2020",
        status: "Active",
    },
    {
        id: "EMP037",
        name: "Layla Young",
        position: "Research Analyst",
        department: "Marketing",
        joiningDate: "13th November 2021",
        status: "Active",
    },
    {
        id: "EMP038",
        name: "Owen Hernandez",
        position: "Security Engineer",
        department: "IT",
        joiningDate: "28th December 2022",
        status: "Inactive",
    },
    {
        id: "EMP039",
        name: "Jack Harris",
        position: "Business Development Manager",
        department: "Sales",
        joiningDate: "2nd January 2023",
        status: "Active",
    },
    {
        id: "EMP040",
        name: "Daniel Martinez",
        position: "System Architect",
        department: "IT",
        joiningDate: "9th February 2021",
        status: "Active",
    },
    {
        id: "EMP041",
        name: "Michael Gonzalez",
        position: "Scrum Master",
        department: "IT",
        joiningDate: "21st March 2020",
        status: "Inactive",
    },
    {
        id: "EMP042",
        name: "Lucas Lopez",
        position: "Software Architect",
        department: "IT",
        joiningDate: "8th April 2021",
        status: "Active",
    },
    {
        id: "EMP043",
        name: "Elijah Clark",
        position: "UX Researcher",
        department: "Design",
        joiningDate: "14th May 2022",
        status: "Active",
    },
    {
        id: "EMP044",
        name: "Jack Robinson",
        position: "Data Engineer",
        department: "IT",
        joiningDate: "30th June 2023",
        status: "Inactive",
    },
    {
        id: "EMP045",
        name: "Jackson Rodriguez",
        position: "Digital Strategist",
        department: "Marketing",
        joiningDate: "22nd July 2019",
        status: "Active",
    },
    {
        id: "EMP046",
        name: "Avery Lewis",
        position: "IT Manager",
        department: "IT",
        joiningDate: "7th August 2021",
        status: "Active",
    },
    {
        id: "EMP047",
        name: "Sofia Walker",
        position: "Front-end Developer",
        department: "IT",
        joiningDate: "19th September 2020",
        status: "Inactive",
    },
    {
        id: "EMP048",
        name: "Scarlett Hall",
        position: "Operations Analyst",
        department: "Operations",
        joiningDate: "12th October 2021",
        status: "Active",
    },
    {
        id: "EMP049",
        name: "Liam Young",
        position: "Database Administrator",
        department: "IT",
        joiningDate: "24th November 2022",
        status: "Active",
    },
    {
        id: "EMP050",
        name: "Emily King",
        position: "Product Designer",
        department: "Design",
        joiningDate: "15th December 2020",
        status: "Inactive",
    },
    {
        id: "EMP051",
        name: "Amelia Allen",
        position: "Risk Manager",
        department: "Finance",
        joiningDate: "7th January 2023",
        status: "Active",
    },
    {
        id: "EMP052",
        name: "Mason Hernandez",
        position: "Chief Technology Officer",
        department: "Management",
        joiningDate: "28th February 2021",
        status: "Active",
    },
    {
        id: "EMP053",
        name: "Ethan Scott",
        position: "Chief Financial Officer",
        department: "Management",
        joiningDate: "11th March 2022",
        status: "Inactive",
    },
    {
        id: "EMP054",
        name: "Sophia Harris",
        position: "Head of Marketing",
        department: "Marketing",
        joiningDate: "6th April 2023",
        status: "Active",
    },
    {
        id: "EMP055",
        name: "James Adams",
        position: "Head of Sales",
        department: "Sales",
        joiningDate: "18th May 2020",
        status: "Active",
    },
    {
        id: "EMP056",
        name: "Mia Baker",
        position: "Head of Design",
        department: "Design",
        joiningDate: "22nd June 2021",
        status: "Inactive",
    },
    {
        id: "EMP057",
        name: "Harper Mitchell",
        position: "Chief Operating Officer",
        department: "Management",
        joiningDate: "5th July 2022",
        status: "Active",
    },
    {
        id: "EMP058",
        name: "Evelyn Perez",
        position: "Chief Executive Officer",
        department: "Management",
        joiningDate: "13th August 2019",
        status: "Active",
    },
    {
        id: "EMP059",
        name: "Alexander Roberts",
        position: "Head of IT",
        department: "IT",
        joiningDate: "27th September 2020",
        status: "Inactive",
    },
    {
        id: "EMP060",
        name: "Sebastian Lewis",
        position: "Legal Counsel",
        department: "Legal",
        joiningDate: "30th October 2021",
        status: "Active",
    },
    {
        id: "EMP061",
        name: "Zoey Hill",
        position: "Project Coordinator",
        department: "Management",
        joiningDate: "22nd November 2022",
        status: "Active",
    },
    {
        id: "EMP062",
        name: "Levi Ramirez",
        position: "Compliance Specialist",
        department: "Legal",
        joiningDate: "15th December 2019",
        status: "Inactive",
    },
    {
        id: "EMP063",
        name: "Grace Martinez",
        position: "Training Specialist",
        department: "Human Resources",
        joiningDate: "1st January 2021",
        status: "Active",
    },
    {
        id: "EMP064",
        name: "Layla Anderson",
        position: "Supply Chain Manager",
        department: "Operations",
        joiningDate: "18th February 2022",
        status: "Active",
    },
    {
        id: "EMP065",
        name: "Owen Thomas",
        position: "Inventory Specialist",
        department: "Operations",
        joiningDate: "9th March 2023",
        status: "Inactive",
    },
    {
        id: "EMP066",
        name: "Jack Rodriguez",
        position: "E-commerce Manager",
        department: "Sales",
        joiningDate: "25th April 2020",
        status: "Active",
    },
    {
        id: "EMP067",
        name: "Daniel Walker",
        position: "Content Strategist",
        department: "Marketing",
        joiningDate: "14th May 2021",
        status: "Active",
    },
    {
        id: "EMP068",
        name: "Michael Harris",
        position: "Community Manager",
        department: "Marketing",
        joiningDate: "30th June 2022",
        status: "Inactive",
    },
    {
        id: "EMP069",
        name: "Lucas Gonzalez",
        position: "Social Media Strategist",
        department: "Marketing",
        joiningDate: "18th July 2023",
        status: "Active",
    },
    {
        id: "EMP070",
        name: "Elijah Lopez",
        position: "PR Specialist",
        department: "Marketing",
        joiningDate: "12th August 2019",
        status: "Active",
    },
    {
        id: "EMP071",
        name: "Jack Robinson",
        position: "Customer Success Manager",
        department: "Customer Support",
        joiningDate: "5th September 2020",
        status: "Inactive",
    },
    {
        id: "EMP072",
        name: "Jackson Lewis",
        position: "Account Manager",
        department: "Sales",
        joiningDate: "27th October 2021",
        status: "Active",
    },
    {
        id: "EMP073",
        name: "Avery Walker",
        position: "Key Account Manager",
        department: "Sales",
        joiningDate: "10th November 2022",
        status: "Active",
    },
    {
        id: "EMP074",
        name: "Sofia Allen",
        position: "Content Editor",
        department: "Marketing",
        joiningDate: "22nd December 2023",
        status: "Inactive",
    },
    {
        id: "EMP075",
        name: "Scarlett Hall",
        position: "Video Producer",
        department: "Marketing",
        joiningDate: "7th January 2021",
        status: "Active",
    },
    {
        id: "EMP076",
        name: "Liam Young",
        position: "Photographer",
        department: "Marketing",
        joiningDate: "28th February 2022",
        status: "Active",
    },
    {
        id: "EMP077",
        name: "Emily King",
        position: "SEO Manager",
        department: "Marketing",
        joiningDate: "17th March 2023",
        status: "Inactive",
    },
    {
        id: "EMP078",
        name: "Amelia Hernandez",
        position: "Marketing Analyst",
        department: "Marketing",
        joiningDate: "15th April 2019",
        status: "Active",
    },
    {
        id: "EMP079",
        name: "Mason Scott",
        position: "Brand Manager",
        department: "Marketing",
        joiningDate: "23rd May 2020",
        status: "Active",
    },
    {
        id: "EMP080",
        name: "Ethan Harris",
        position: "PPC Specialist",
        department: "Marketing",
        joiningDate: "19th June 2021",
        status: "Inactive",
    },
    {
        id: "EMP081",
        name: "Sophia Adams",
        position: "Email Marketing Specialist",
        department: "Marketing",
        joiningDate: "11th July 2022",
        status: "Active",
    },
    {
        id: "EMP082",
        name: "James Baker",
        position: "Customer Support Manager",
        department: "Customer Support",
        joiningDate: "5th August 2023",
        status: "Active",
    },
    {
        id: "EMP083",
        name: "Mia Mitchell",
        position: "Technical Support Specialist",
        department: "Customer Support",
        joiningDate: "29th September 2020",
        status: "Inactive",
    },
    {
        id: "EMP084",
        name: "Harper Perez",
        position: "Product Support Specialist",
        department: "Customer Support",
        joiningDate: "22nd October 2021",
        status: "Active",
    },
    {
        id: "EMP085",
        name: "Evelyn Roberts",
        position: "Onboarding Specialist",
        department: "Customer Support",
        joiningDate: "8th November 2022",
        status: "Active",
    },
    {
        id: "EMP086",
        name: "Alexander Lewis",
        position: "Customer Experience Manager",
        department: "Customer Support",
        joiningDate: "14th December 2023",
        status: "Inactive",
    },
    {
        id: "EMP087",
        name: "Sebastian Hill",
        position: "Customer Success Specialist",
        department: "Customer Support",
        joiningDate: "1st January 2020",
        status: "Active",
    },
    {
        id: "EMP088",
        name: "Zoey Ramirez",
        position: "Customer Feedback Manager",
        department: "Customer Support",
        joiningDate: "27th February 2021",
        status: "Active",
    },
    {
        id: "EMP089",
        name: "Levi Martinez",
        position: "Quality Assurance Manager",
        department: "Quality Assurance",
        joiningDate: "19th March 2022",
        status: "Inactive",
    },
    {
        id: "EMP090",
        name: "Grace Anderson",
        position: "Testing Lead",
        department: "Quality Assurance",
        joiningDate: "7th April 2023",
        status: "Active",
    },
    {
        id: "EMP091",
        name: "Layla Thomas",
        position: "Automation Tester",
        department: "Quality Assurance",
        joiningDate: "15th May 2019",
        status: "Active",
    },
    {
        id: "EMP092",
        name: "Owen Rodriguez",
        position: "Manual Tester",
        department: "Quality Assurance",
        joiningDate: "10th June 2020",
        status: "Inactive",
    },
    {
        id: "EMP093",
        name: "Jack Walker",
        position: "Performance Tester",
        department: "Quality Assurance",
        joiningDate: "23rd July 2021",
        status: "Active",
    },
    {
        id: "EMP094",
        name: "Jackson Harris",
        position: "Usability Tester",
        department: "Quality Assurance",
        joiningDate: "8th August 2022",
        status: "Active",
    },
    {
        id: "EMP095",
        name: "Avery Gonzalez",
        position: "Security Tester",
        department: "Quality Assurance",
        joiningDate: "27th September 2023",
        status: "Inactive",
    },
    {
        id: "EMP096",
        name: "Sofia Lopez",
        position: "QA Analyst",
        department: "Quality Assurance",
        joiningDate: "3rd October 2019",
        status: "Active",
    },
    {
        id: "EMP097",
        name: "Scarlett Robinson",
        position: "QA Engineer",
        department: "Quality Assurance",
        joiningDate: "14th November 2020",
        status: "Active",
    },
    {
        id: "EMP098",
        name: "Liam Lewis",
        position: "QA Lead",
        department: "Quality Assurance",
        joiningDate: "28th December 2021",
        status: "Inactive",
    },
    {
        id: "EMP099",
        name: "Emily Young",
        position: "QA Manager",
        department: "Quality Assurance",
        joiningDate: "19th January 2023",
        status: "Active",
    },
    {
        id: "EMP100",
        name: "Amelia King",
        position: "QA Director",
        department: "Quality Assurance",
        joiningDate: "15th February 2020",
        status: "Active",
    },
];
